server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: admin:Cr8rAFpybbGN01Ou3mUV@tcp(allendigital.cluster-cucaba7nklrl.ap-south-1.rds.amazonaws.com:3306)/usersdb
    max_idle_conns: 10
    max_open_conns: 100
    max_conn_lifetime_in_mins: 60
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
